name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - uses: actions/checkout@v3
    - run: echo "${{ secrets.STOCKINVESTMENTHELPER_PROPERTIES_PROD }}" >> ./src/main/resources/application-prod.properties
    - run: cat ./src/main/resources/application-prod.properties
